### ISSUE TITLE
Please add support for multiple real servers serving same ip address (ie load balancing of legit traffic)

### ISSUE THREAD

**Issue by bazuchan** [LTD-Beget/syncookied#67]
For example hosts.yml would look like this:
```
- ip: 1.1.1.1
  - srv1:
    secrets_addr: udp://2.2.2.1:1111
    mac: 02:02:02:02:02:01
  - srv2:
    secrets_addr: udp://2.2.2.2:1111
    mac: 02:02:02:02:02:02
  - srv3:
    secrets_addr: udp://2.2.2.3:1111
    mac: 02:02:02:02:02:03
```
So packets would be sent to srv1-3 based on hash of src ip:port. Adding a weighted balancing might be useful too.
